name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'

jobs:
    full-test:
        runs-on: self-hosted
        timeout-minutes: 150
        steps:
          - uses: webfactory/ssh-agent@v0.5.3
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          - uses: actions/checkout@v3
            with:
              submodules: recursive

          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh

          - name: Cleanup
            if: always()
            run: ssh-add -D

